### PR TITLE
Report not source diagnostics

### PR DESCRIPTION
**Pull request by divan-9**
In case of exception in analyzer it would be reported as AD0001 diagnostic. It has no location in source tree.

Sometimes it can be useful to check absence of exception by unit test 

For instance

```
        [Fact]
        public void DoesNotWarnEmptyArgumentList()
        {
            const string code = @"
                class A
                {
                    void Method()
                    {
                    }
                }
            ";

            this.NoDiagnostic(code, "AD0001");
        }
```

Honestly I don't really understand why this check exists in original version, and if my solution is  totally wrong just let me know.

### CODE REVIEW

**Comment by cezarypiatek** [comment]
Thanks, I wasn't aware of `AD0001`.  Maybe I should add dedicated assertion that checks if there is no `AD0001` or maybe `GetDiagnostics` should throw an exception in that case?

**Comment by divan-9** [comment]
You right, special exception is better solution

**Comment by cezarypiatek** [comment]
Do you mean that options with throwing an exception from `GetDiagnostics`?  That would give confidence that no exception is thrown the analyzer. 
Let's say your assertion is `NoDiagnostic("XYZ0001") - this assertion is meet even if the analyzer throws an exception but it's rather not expected behavior.

**Comment by divan-9** [comment]
I mean the solution with specific assertion like `HasNoException(source)`

Another option with throwing exception from GetDiagnostic is OK to, but testing this scenario is usualy looks less expressive.

Checking exceptions in unit tests is usually result of working on reported bugs, it's not common for normal TDD cycle, but sometimes it could be helpfull.

I can try to create another pull request in a while

**Pull request merged**
